# .___  _                     .                     .       __               .        _
# /   \ /        ___  , __   _/_     __.  , _ , _   /       |    __.  .___   |     ___/   ____
# |,_-' |,---.  /   ` |'  `.  |    .'   \ |' `|' `. |       |  .'   \ /   \  |    /   |  (
# |     |'   ` |    | |    |  |    |    | |   |   | |  /\   /  |    | |   '  |   ,'   |  `--.
# /     /    | `.__/| /    |  \__/  `._.' /   '   / |,'  \,'    `._.' /     /\__ `___,' \___.'

name: PhantomWorlds
version: ${project.version}
description: ${project.description}
authors: [ 'lokka30' ]

main: me.lokka30.phantomworlds.PhantomWorlds
api-version: '1.13'

website: 'https://www.spigotmc.org'

commands:
  phantomworlds:
    description: Create, manage or teleport to worlds!
    aliases: [ pworlds, phantomworld, pworld, pw ]
    usage: /<command> <create/unload/teleport/tp/list/spawn/setspawn>

permissions:
  phantomworlds.*:
    description: All permissions.
    default: op
    children:
      phantomworlds.create: true
      phantomworlds.import: true
      phantomworlds.unload: true
      phantomworlds.teleport: true
      phantomworlds.list: true
      phantomworlds.spawn: true
      phantomworlds.spawn.others: true
      phantomworlds.setspawn: true
      phantomworlds.vanishcheckbypass: true
  phantomworlds.create:
    default: op
    description: create subcommand
  phantomworlds.unload:
    default: op
    description: unload subcommand
  phantomworlds.teleport:
    default: op
    description: teleport subcommand
  phantomworlds.list:
    default: op
    description: list subcommand
  phantomworlds.spawn:
    default: op
    description: spawn subcommand
  phantomworlds.spawn.others:
    default: op
    description: teleport other players in spawn subcommand
  phantomworlds.setspawn:
    default: op
    description: setspawn subcommand
  phantomworlds.vanishbypass:
    default: op
    description: subcommands will not factor in if players with this permission can or can't see vanished players