# .___  _                     .                     .       __               .        _
# /   \ /        ___  , __   _/_     __.  , _ , _   /       |    __.  .___   |     ___/   ____
# |,_-' |,---.  /   ` |'  `.  |    .'   \ |' `|' `. |       |  .'   \ /   \  |    /   |  (
# |     |'   ` |    | |    |  |    |    | |   |   | |  /\   /  |    | |   '  |   ,'   |  `--.
# /     /    | `.__/| /    |  \__/  `._.' /   '   / |,'  \,'    `._.' /     /\__ `___,' \___.'

name: 'PhantomWorlds'
version: '${project.version}'
description: '${project.description}'
author: 'lokka30'
website: 'https://github.com/lokka30/PhantomWorlds'

main: 'me.lokka30.phantomworlds.PhantomWorlds'
api-version: '1.13'
load: 'STARTUP'

commands:
  phantomworlds:
    description: 'Create, manage or teleport to worlds.'
    aliases: [ 'pw', 'world' ]
    usage: '/<command>'

#TODO
permissions:
  phantomworlds.command.see_vanished_users:
    default: 'op'
    description: 'subcommands will not factor in if players with this permission can or can''t see vanished players'